### ISSUE TITLE
Add legal/licensing information in Native Gateway project repos

### ISSUE THREAD

**Issue by osmanzeki** [vedi/native-gateway-aggregated-android#1]
Hi,

I studied your native extension library and it is really helpful and well-made but I would need to know under which license you are planning on distributing the library as I may need to modify/extend it to adapt it to a project and I would need to know what you would like to set as terms of usage.

I'm not going to create an issue in everyone of your Native Gateway projects but I think you could apply it to all of them if you want to encourage people using your code without having them worry about licensing.

This is a great website to compare available licenses:
http://choosealicense.com/

I usually prefer to use MIT for open-source projects as it is permissive for commercial usage and modification but also makes sure the copyright for the code stays yours and yours only.

**Comment by vedi** [comment]
Thank you for your question, I'm considering to use a free license. Will http://opensource.org/licenses/Apache-2.0 work well for you?

**Comment by osmanzeki** [comment]
That license seems perfect and clear as to the usage terms. Thank you for your reply. :)
